#pragma once
#include <iostream>
#include <vector>
#include <regex>
#include <string>


//TOKENS
#define FIM "FIM"
#define FIM_PROGRAMA "FIM_PROGRAMA"

#define IDENTIFICADOR "IDENTIFICADOR"
#define NUM_INT "NUMERO_INTEIRO"
#define NUM_REAL "NUMERO_REAL" 

#define CARACTERE "CARACTERE"
#define STRING "STRING"

//CARACTERES
#define TAB 9
#define FIM_LINHA 10
#define ESPACO ' '

//PALAVRAS RESERVADAS
#define TIPO_BOOLEANO "TIPO_BOOLEANO"
#define TIPO_CHAR "TIPO_CHAR"
#define TIPO_FLOAT "TIPO_FLOAT"
#define TIPO_INT "TIPO_INT"
#define TIPO_VOID "TIPO_VOID"
#define TIPO_STRING "TIPO_STRING"
#define LACO_DO "LACO_DO"
#define LACO_FOR "LACO_FOR"
#define LACO_WHILE "LACO_WHILE"
#define LACO_BREAK "LACO_BREAK"
#define LACO_CONTINUE "LACO_CONTINUE"
#define LACO_TO "LACO_TO" 
#define LACO_NEXT "LACO_NEXT" 
#define LACO_REPEAT "LACO_REPEAT" 
#define LACO_UNTIL "LACO_UNTIL"
#define LACO_LOOP "LACO_LOOP"

#define CONDICAO_IF "CONDICAO_IF"
#define CONDICAO_ELSE "CONDICAO_ELSE"
#define CONDICAO_ENDIF "CONDICAO_ENDIF" 
#define CONDICAO_THEN "CONDICAO_THEN" 

#define VERDADEIRO "VERDADEIRO"
#define FALSO "FALSO"

#define RETORNO "RETORNO"
#define GOTO "GOTO"

#define CONSTANTE "CONSTANTE"
#define SUB "SUB"
#define END_SUB "END_SUB"
#define VAR "VAR"
#define FUNCTION "FUNCTION"
#define END_FUNCTION "END_FUNCTION"
#define BY "BY" 
#define VALUE "VALUE" 
#define REF "REF" 
#define PRINT "PRINT" 
#define PRINTLN "PRINTLN" 
#define SCAN "SCAN" 
#define SCANLN "SCANLN" 

//OPERADORES
#define OP_ADICAO "OP_ADICAO"
#define OP_SUBTRACAO "OP_SUBTRACAO"
#define OP_MULTIPLICACAO "OP_MULTIPLICACAO"
#define OP_DIVISAO "OP_DIVISAO"
#define OP_RESTO "OP_RESTO"
#define OP_MOD "OP_MOD"

#define OP_MAIOR "OP_MAIOR"
#define OP_MENOR "OP_MENOR"
#define OP_MAIOR_IGUAL "OP_MAIOR_IGUAL"
#define OP_MENOR_IGUAL "OP_MENOR_IGUAL"

#define OP_DIFERENTE "OP_DIFERENTE" 
#define OP_IGUALDADE "OP_IGUALDADE"
#define OP_ATRIBUICAO "OP_ATRIBUICAO"

#define OP_NEGACAO "OP_NEGACAO" 
#define OP_NEGA_IGUALDADE "OP_NEGA_IGUALDADE"

#define OP_ATRIBUICAO_ADICAO "OP_ATRIBUICAO_ADICAO"
#define OP_ATRIBUICAO_SUBTRACAO "OP_ATRIBUICAO_SUBTRACAO"
#define OP_ATRIBUICAO_MULTIPLICACAO "OP_ATRIBUICAO_MULTIPLICACAO"
#define OP_ATRIBUICAO_DIVISAO "OP_ATRIBUICAO_DIVISAO"
#define OP_ATRIBUICAO_RESTO "OP_ATRIBUICAO_RESTO"

#define OP_LOGICO_E "OP_LOGICO_E"
#define OP_LOGICO_OU "OP_LOGICO_OU"

#define OP_INCREMENTO "OP_INCREMENTO"
#define OP_DECREMENTO "OP_DECREMENTO"

#define OP_SELECAO_IDENTIFICADOR "OP_SELECAO_IDENTIFICADOR"
#define OP_SELECAO_PONTEIRO "OP_SELECAO_PONTEIRO"


#define ENDERECO_ELEMENTO "ENDERECO_ELEMENTO"

//SINAIS DE PONTUAÇÃO
#define  VIRGULA "VIRGULA"
#define  PONTO_VIRGULA "PONTO_VIRGULA"
#define  ABRE_PARENTESES "ABRE_PARENTESES"
#define  FECHA_PARENTESES "FECHA_PARENTESES"
#define  ABRE_COLCHETES "ABRE_COLCHETES"
#define  FECHA_COLCHETES "FECHA_COLCHETES"
#define  ABRE_CHAVES "ABRE_CHAVES"
#define  FECHA_CHAVES "FECHA_CHAVES"
#define PONTO_INTERROGACAO "PONTO_INTERROGACAO"
#define DOIS_PONTOS "DOIS_PONTOS"